### ISSUE TITLE
godot beta 3 crash when importing this asset !

### ISSUE THREAD

**Issue by aztecsensei** [dgilmarj/godot-first-person-character#1]
hello i cant open this asset, i was trying the new beta 3 but it looks like it doesnt work with it.
hope it can be fix i really wanted to try this nice asset.

thanks in advance.

**Comment by aztecsensei** [comment]
sorry i just rename it and now works fine.
:)

**Comment by dgilmarj** [comment]
thks, if have any other issue, please let me know I will try to help.
